Repository YetiTool/easycut-smartbench, pull requests merged in 2024-03, with the labels that each got.

#1577 Benji/path utils
  src/asmcnc/core_UI/path_utils.py
Labels: member: Benji, size: small PR

#1563 Benji/2636/probing screen
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
  src/asmcnc/comms/foreign_dictionary.txt
  src/asmcnc/comms/router_machine.py
  src/asmcnc/core_UI/components/buttons/__init__.py
  src/asmcnc/core_UI/components/buttons/probe_button.py
  src/asmcnc/skavaUI/img/z_probe_big.png
  src/asmcnc/skavaUI/screen_home.py
  src/asmcnc/skavaUI/screen_probing.py
  src/asmcnc/skavaUI/widget_z_move.py
Labels: member: Benji, status: changes requested, size: medium PR

#1579 Archie/z retract
  src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/core_UI/job_go/screens/screen_spindle_health_check.py
  src/asmcnc/skavaUI/screen_spindle_shutdown.py
Labels: member: Archie, status: ready for review, size: medium PR, priority: 1

#1580 decide weither upgrade should be shown or not
  src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/skavaUI/screen_lobby.py
Labels: member: Marc, status: ready for review, priority: 2, type: feature, project: dwt

#1586 Handle machine specific settings
  src/asmcnc/comms/grbl_settings_manager.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/serial_connection.py
  src/main.py
Labels: member: Marc, size: small PR, status: approved, priority: 1, type: feature

#1585 Benji/path utils update
  src/asmcnc/core_UI/path_utils.py
  tests/test_path_utils.py
Labels: member: Benji, status: ready for review, size: medium PR

#1589 start_sequential_streaming can now be called simultaneously
  src/asmcnc/comms/grbl_settings_manager.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/serial_connection.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 2, type: bug

#1587 Benji/r282/yp profiles
  src/asmcnc/comms/foreign_dictionary.txt
  src/asmcnc/job/yetipilot/config/profiles.json
Labels: member: Benji, priority: 1

#1595 Make geberit shape rotatable
  src/asmcnc/apps/drywall_cutter_app/img/geberit_dims.png
  src/asmcnc/apps/drywall_cutter_app/img/geberit_horizontal_dims.png
  src/asmcnc/apps/drywall_cutter_app/img/geberit_vertical_dims.png
  src/asmcnc/apps/drywall_cutter_app/img/geberit_vertical_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: size: small PR, type: feature, project: dwt

#1597 Change floatinput to set float type by default
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
  src/asmcnc/core_UI/components/FloatInput.py
Labels: size: small PR, type: feature, project: dwt

#1596 Fix slider graphic
  src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
  tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Labels: size: small PR, type: bug

#1590 Remove sm from serial
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/skavaUI/screen_go.py
  src/asmcnc/skavaUI/widget_gcode_monitor.py
  tests/automated_unit_tests/comms/test_serial_connection_events.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 3, type: feature

#1581 Drywall fix unit switch
  src/asmcnc/apps/drywall_cutter_app/img/unit_toggle.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: size: small PR, type: feature, project: dwt

#1606 Implement Z datum reminder dismiss
  src/asmcnc/core_UI/components/buttons/probe_button.py
  src/asmcnc/skavaUI/screen_home.py
Labels: size: small PR, priority: 1, type: bug

#1607 Archie/smarttransfer
  ansible/init.yaml
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/smart_transfer/__init__.py
  src/asmcnc/comms/smart_transfer/server_connection.py
  src/asmcnc/comms/smart_transfer/smb.conf
  src/lower_beam_qc_app.py
  src/main.py
  src/z_head_qc_app.py
  tests/manual_tests/experiments/experiment_toggle_reset_pin.py
  tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 1, type: feature

#1602 Increased timeout timer to 45s
  src/asmcnc/apps/wifi_app/screen_wifi.py
Labels: member: Vlad, size: small PR, status: approved

#1601 Defocusing all text inputs on popup dismiss
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: member: Vlad, size: small PR, status: approved, project: dwt

#1254 Wifi confirmation popup
  src/asmcnc/apps/wifi_app/screen_wifi.py
Labels: member: Vlad, status: ready for review, size: small PR

#1599 Made keyboard move on collision and input filters
  src/asmcnc/core_UI/components/FloatInput.py
  src/asmcnc/keyboard/custom_keyboard.py
Labels: member: Vlad, size: small PR, status: approved, project: dwt

#1605 Archie/dwt config order 2
  src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
  src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py
  src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 2, project: dwt

#1592 Archie/red status widget
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_laser_buttons.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_34.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_35.py
  src/asmcnc/apps/upgrade_app/screen_upgrade.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/core_UI/components/buttons/button_base.py
  src/asmcnc/core_UI/components/buttons/spindle_button.py
  src/asmcnc/core_UI/components/buttons/vacuum_button.py
  src/asmcnc/core_UI/components/float_input.py
  src/asmcnc/core_UI/components/widgets/blinking_widget.py
  src/asmcnc/core_UI/job_go/screens/screen_spindle_health_check.py
  src/asmcnc/core_UI/scaling_utils.py
  src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py
  src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc_warranty.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_1.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_2.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
  src/asmcnc/skavaUI/img/extraction_on.png
  src/asmcnc/skavaUI/img/off_icon.png
  src/asmcnc/skavaUI/img/spindle_off.png
  src/asmcnc/skavaUI/img/spindle_on.png
  src/asmcnc/skavaUI/screen_go.py
  src/asmcnc/skavaUI/screen_spindle_cooldown.py
  src/asmcnc/skavaUI/widget_common_move.py
Labels: member: Archie, status: ready for review, size: medium PR, priority: 1, type: feature

#1299 Drywall canvas bumpers
  src/asmcnc/apps/drywall_cutter_app/config/cutters/test_cutter2.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_8mm.gcode
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Letty

#1300 Drywall canvas max labels
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Letty

#1312 Drywall check datum and extents refactor
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Letty

#1629 Benji/home minirig fix
  src/asmcnc/skavaUI/screen_homing_active.py
  src/asmcnc/skavaUI/widget_quick_commands.py
Labels: member: Benji, size: small PR

#1630 Vp/2736/big text inputs
  src/asmcnc/apps/drywall_cutter_app/img/rectangle_horizontal_dims.png
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Vlad, status: ready for review, size: small PR, project: dwt

#1632 Depth per pass warning shows as you type
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: member: Vlad, status: ready for review, size: small PR, project: dwt

#1253 Incorrect shutdown screen
  src/asmcnc/apps/start_up_sequence/screens/img/correct-shutdown-qr.png
  src/asmcnc/apps/start_up_sequence/screens/screen_incorrect_shutdown.py
  src/asmcnc/apps/start_up_sequence/start_up_sequence_manager.py
  src/asmcnc/apps/systemTools_app/screen_manager_systemtools.py
  src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
  src/asmcnc/comms/foreign_dictionary.txt
  src/asmcnc/core_UI/console_utils.py
  src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc.py
  src/asmcnc/production/lower_beam_qc_jig/lower_beam_qc_warranty.py
  src/asmcnc/production/lowerbeam_calibration_jig/lowerbeam_calibration_success.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_aftr_apr_21.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_b4_apr_21.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_home.py
  src/asmcnc/skavaUI/img/shutdown_black.png
  src/asmcnc/skavaUI/popup_info.py
  src/asmcnc/skavaUI/screen_lobby.py
  src/asmcnc/skavaUI/screen_rebooting.py
  src/jobCache/.gitignore
  src/main.py
  src/settings/settings_manager.py
Labels: member: Vlad, status: changes requested, size: big PR

#1640 Drywall visual fixes
  src/asmcnc/apps/drywall_cutter_app/img/unit_toggle.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
Labels: size: small PR, type: feature, project: dwt

#1641 Disable job recovery on drywall machines
  src/asmcnc/skavaUI/screen_home.py
Labels: size: small PR, type: feature, project: dwt

#1636 Engine pr
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_90deg.json
  src/asmcnc/apps/drywall_cutter_app/engine.py
  tests/test_engine.py
Labels: member: Benji, size: big PR, project: dwt

#1612 Remove sm from serial
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/skavaUI/screen_check_job.py
  src/asmcnc/skavaUI/screen_go.py
  tests/automated_unit_tests/comms/test_serial_connection_events.py
Labels: member: Marc, size: small PR, status: approved, priority: 2

#1642 Vp/2458/dwt yp
  src/asmcnc/apps/app_manager.py
  src/asmcnc/apps/drywall_cutter_app/config/configurations/test_config
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_45deg.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_60deg.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_90deg.json
  src/asmcnc/apps/drywall_cutter_app/job_load_helper.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/core_UI/job_go/popups/popup_yetipilot_settings.py
  src/asmcnc/core_UI/job_go/widgets/widget_yeti_pilot.py
  src/asmcnc/job/yetipilot/config/profiles.json
  src/asmcnc/skavaUI/screen_go.py
Labels: member: Vlad, status: ready for review, size: big PR, priority: 1, project: dwt

#1643 Engine pr
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Labels: member: Benji, size: medium PR, project: dwt
