Repository YetiTool/easycut-smartbench, pull requests merged in 2024-02, with the labels that each got.

#1540 Show shapecutter on big console
  src/asmcnc/skavaUI/screen_lobby.py
Labels: size: small PR, project: c10

#1538 archie/scaling/scaling_utils
  src/asmcnc/core_UI/scaling_utils.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 1, type: feature, project: c10

#1536 Archie/2642/fix_leftover_test
  src/asmcnc/comms/router_machine.py
  tests/automated_unit_tests/comms/test_smartbench_model_detection.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 3, type: bug

#1545 Benji/2638/spindle rpm fix
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/production/z_head_qc_jig/z_head_qc_2.py
  src/asmcnc/skavaUI/screen_file_loading.py
  tests/automated_unit_tests/comms/test_router_machine_spindle_rpm.py
  tests/automated_unit_tests/comms/test_serial_connection_streaming_units.py
Labels: member: Benji, status: ready for review, size: medium PR

#1542 Archie/dwt/new configuration
  src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
  src/asmcnc/apps/drywall_cutter_app/config/configurations/__init__.py
  src/asmcnc/apps/drywall_cutter_app/config/configurations/test_config
  src/asmcnc/apps/drywall_cutter_app/config/cutters/__init__.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Labels: member: Archie, size: small PR, priority: 2, type: feature, status: in review, project: dwt

#1546 Job recovery r handling
  src/asmcnc/job/job_data.py
  src/asmcnc/skavaUI/screen_job_recovery.py
  tests/automated_unit_tests/job/test_generate_recovery_gcode.py
Labels: size: small PR, type: bug, project: dwt

#1551 Benji/2670/yp spindle rpm fix
  src/asmcnc/comms/router_machine.py
  src/asmcnc/job/yetipilot/yetipilot.py
Labels: member: Benji, status: ready for review, size: medium PR

#1544 Vp/2437/material setup confirm buttons
  src/asmcnc/apps/app_manager.py
  src/asmcnc/apps/drywall_cutter_app/img/bottom_offset_graphic.png
  src/asmcnc/apps/drywall_cutter_app/img/cutter_graphic.png
  src/asmcnc/apps/drywall_cutter_app/img/material_graphic.png
  src/asmcnc/apps/drywall_cutter_app/img/material_thickness_dims.png
  src/asmcnc/apps/drywall_cutter_app/img/pass_depth_line.png
  src/asmcnc/apps/drywall_cutter_app/img/total_cut_depth_bottom_arrow.png
  src/asmcnc/apps/drywall_cutter_app/img/total_cut_depth_dims.png
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/main.py
Labels: status: ready for review, size: small PR, type: feature, project: dwt

#1552 Archie/dwt rebrand/2451
  src/asmcnc/comms/localization.py
  src/asmcnc/comms/model_detector.py
  tests/automated_unit_tests/comms/test_localization_product_name.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 2, type: feature, project: dwt

#1554 Archie/dwt rebrand/2448
  src/asmcnc/comms/localization.py
  src/asmcnc/comms/model_detector.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/skavaUI/img/dwt_splash_screen.png
  src/asmcnc/skavaUI/img/yeti_splash_screen.png
  src/main.py
  tests/automated_unit_tests/comms/test_localization_product_name.py
Labels: member: Archie, size: small PR, priority: 2, type: feature, status: in review

#1534 Updated keyboard logic and numeric layout
  src/asmcnc/keyboard/custom_keyboard.py
  src/asmcnc/keyboard/layouts/numeric.json
Labels: status: ready for review, size: small PR, type: feature

#1558 Added logic to handle deletion of selected text
  src/asmcnc/keyboard/custom_keyboard.py
Labels: status: ready for review, size: small PR, type: feature

#1296 Drywall canvas further changes
  src/asmcnc/apps/drywall_cutter_app/img/geberit_vertical_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/img/go_to_datum_pulse.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
  src/asmcnc/comms/router_machine.py
Labels: member: Letty

#1548 Display machine state in drywall app
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/comms/serial_connection.py
Labels: size: small PR, type: feature, status: in review, project: dwt

#1306 Drywall overlay bug
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
Labels: member: Letty

#1307 Drywall proper config loading
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Letty

#1561 Add labels to canvas text inputs
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: size: small PR, type: feature, project: dwt

#1564 Marc/detect model 50
  src/asmcnc/apps/systemTools_app/screens/screen_build_info.py
  src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
  src/asmcnc/comms/localization.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
  src/asmcnc/skavaUI/screen_lobby.py
  src/main.py
  tests/automated_unit_tests/comms/test_localization_product_name.py
  tests/automated_unit_tests/comms/test_smartbench_model_detection.py
Labels: member: Marc, status: ready for review, size: medium PR, priority: 2, type: security

#1566 Marc/detect model 50
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/product_code_migration/migration.json
  src/asmcnc/comms/product_code_migration/migration_raw.json
  src/main.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 2, type: feature

#1565 Vp/2674/shape display custom kb
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: status: ready for review, size: small PR, project: dwt

#1569 Updated depth per pass text logic
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: status: ready for review, size: small PR, project: dwt

#1571 Dwt canvas fix text inputs
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Dennis, size: small PR, type: feature, project: dwt

#1570 Added mechanism for setting a fixed keyboard position
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/keyboard/custom_keyboard.py
Labels: status: ready for review, size: medium PR, project: dwt

#1572 Drywall canvas units
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Dennis, size: small PR, type: feature, project: dwt

#1568 Validating input after lose of focus
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: status: ready for review, size: small PR, project: dwt

#1297 Drywall fast probe
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
  src/asmcnc/comms/router_machine.py
Labels: member: Letty

#1574 Archie/dwt rebrand/smartbench name
  src/asmcnc/comms/model_manager.py
Labels: member: Archie, size: small PR, status: approved, priority: 2, project: dwt

#1575 Archie/dwt rebrand/warranty sequence
  src/asmcnc/apps/start_up_sequence/warranty_app/screen_manager_warranty.py
  src/asmcnc/apps/start_up_sequence/warranty_app/screens/screen_warranty_registration_2.py
Labels: member: Archie, status: ready for review, size: medium PR, priority: 2, project: dwt
