Repository YetiTool/easycut-smartbench, pull requests merged in 2024-04, with the labels that each got.

#1651 Engine pr rotate geberit
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_8mm.gcode
Labels: member: Benji, status: ready for review, size: small PR, priority: 1, project: dwt

#1652 Dwt simulation
  src/asmcnc/apps/app_manager.py
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/core_UI/popup_manager.py
  src/asmcnc/core_UI/popups.py
  src/main.py
  tests/test_engine.py
Labels: member: Benji, status: ready for review, size: medium PR, priority: 1, project: dwt

#1663 Vp/2461/keyboard design
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/keyboard/custom_keyboard.py
  src/asmcnc/keyboard/images/background_1280.png
  src/asmcnc/keyboard/images/background_800.png
  src/asmcnc/keyboard/images/numeric_background_1280.png
  src/asmcnc/keyboard/images/numeric_background_800.png
  src/asmcnc/keyboard/layouts/numeric.json
Labels: member: Vlad, status: ready for review, size: medium PR

#1667 Fixed input focus logic
  src/asmcnc/keyboard/custom_keyboard.py
Labels: member: Vlad, status: ready for review, size: small PR

#1665 Benji/dwt/laser
  src/asmcnc/apps/drywall_cutter_app/coordinate_system.py
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
  src/asmcnc/comms/router_machine.py
Labels: member: Benji, status: ready for review, size: medium PR, priority: 1

#1674 Benji/dwt/fix simulation
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/core_UI/popups.py
Labels: member: Benji, status: ready for review, size: medium PR, priority: 1, project: dwt

#1675 Marc/fix restoring system settings
  src/asmcnc/comms/grbl_settings_manager.py
  src/asmcnc/comms/serial_connection.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 1, type: feature

#1694 Benji/dwt/geberit datum return fix
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_8mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_8mm.gcode
Labels: member: Benji, status: ready for review, project: dwt

#1692 Benji/release/seperate release notes
  src/asmcnc/apps/start_up_sequence/screens/screen_release_notes.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/core_UI/path_utils.py
  v290_DrywallTec.txt
  v290_SmartBench.txt
Labels: member: Benji, size: medium PR, status: needs testing

#1695 Marc/refactor labels
  src/asmcnc/apps/SWupdater_app/popup_update_SW.py
  src/asmcnc/apps/SWupdater_app/screen_update_SW.py
  src/asmcnc/apps/maintenance_app/popup_maintenance.py
  src/asmcnc/apps/maintenance_app/screen_maintenance.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_brush_life.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_brush_monitor.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_brush_use.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_health_check.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_spindle_settings.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_touchplate_offset.py
  src/asmcnc/apps/maintenance_app/widget_maintenance_z_lubrication_reminder.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_1.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_14.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_19.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_26.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_33.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_34.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_6.py
  src/asmcnc/apps/shapeCutter_app/screens/screen_shapeCutter_post_job_save.py
  src/asmcnc/apps/upgrade_app/screen_already_upgraded.py
  src/asmcnc/apps/upgrade_app/screen_upgrade.py
  src/asmcnc/apps/upgrade_app/screen_upgrade_successful.py
  src/asmcnc/apps/wifi_app/screen_wifi.py
  src/asmcnc/core_UI/components/labels/__init__.py
  src/asmcnc/core_UI/components/labels/base_label.py
  src/asmcnc/core_UI/hoverable.py
  src/main.py
Labels: member: Marc, status: ready for review, size: medium PR, priority: 2, type: feature

#1699 Dummy file, so the sb_values folder is delivered with a fresh clone
  src/sb_values/tmp
Labels: member: Marc, status: ready for review, size: small PR, priority: 2, type: bug

#1698 Benji/comms/refactor logging
  src/asmcnc/comms/coordinate_system.py
  src/asmcnc/comms/localization.py
  src/asmcnc/comms/logging/log_exporter.py
  src/asmcnc/comms/smart_transfer/server_connection.py
  src/asmcnc/comms/smartbench_flurry_database_connection.py
  src/asmcnc/comms/usb_storage.py
Labels: member: Benji, size: small PR

#1700 added check for text_instance if it was defocused already
  src/asmcnc/comms/product_code_migration/migration.json
  src/asmcnc/keyboard/custom_keyboard.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 1, type: bug

#1696 Systemtools logging
  src/asmcnc/apps/systemTools_app/screens/calibration/screen_calibration_test.py
  src/asmcnc/apps/systemTools_app/screens/calibration/screen_overnight_test.py
  src/asmcnc/apps/systemTools_app/screens/calibration/screen_serial_numbers.py
  src/asmcnc/apps/systemTools_app/screens/calibration/screen_stall_jig.py
  src/asmcnc/apps/systemTools_app/screens/calibration/widget_current_adjustment.py
  src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
Labels: size: small PR

#1613 Restore console specific settings
  src/asmcnc/apps/maintenance_app/screen_maintenance.py
  src/asmcnc/apps/systemTools_app/screens/screen_factory_settings.py
  src/asmcnc/comms/grbl_settings_manager.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
Labels: status: ready for review, size: small PR, type: feature

#1708 archie/fix_paths
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_config_filesaver.py
  src/asmcnc/apps/start_up_sequence/screens/screen_language_selection.py
  src/asmcnc/apps/start_up_sequence/screens/screen_release_notes.py
  src/asmcnc/comms/grbl_settings_manager.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/core_UI/components/buttons/probe_button.py
  src/asmcnc/core_UI/components/buttons/spindle_button.py
  src/asmcnc/core_UI/components/buttons/vacuum_button.py
  src/asmcnc/core_UI/path_utils.py
  src/asmcnc/paths.py
  src/main.py
  src/sb_values/tmp
  tests/test_path_utils.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 2

#1712 fixed verbose output
  src/asmcnc/comms/serial_connection.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 1, type: bug

#1250 Job recovery ignore comments
  src/asmcnc/job/job_data.py
  src/asmcnc/skavaUI/screen_job_recovery.py
  tests/automated_unit_tests/job/test_generate_recovery_gcode.py
Labels: member: Letty
