Repository YetiTool/easycut-smartbench, pull requests merged in 2024-06, with the labels that each got.

#1737 Added tabs setting to material setup popup
  src/asmcnc/apps/drywall_cutter_app/config/config_classes.py
  src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: member: Vlad, status: ready for review, size: small PR

#1734 Add pocket toolpath visuals
  src/asmcnc/apps/drywall_cutter_app/img/circle_pocket_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/img/rectangle_horizontal_pocket_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/img/rectangle_vertical_pocket_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/img/square_pocket_toolpath.png
  src/asmcnc/apps/drywall_cutter_app/img/toolpath_offset_pocket_button.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Labels: size: small PR, type: feature

#1727 default to router in dwt app
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/skavaUI/widget_quick_commands.py
Labels: member: Vlad, status: ready for review, size: small PR

#1743 Disable geberit datum offset
  src/asmcnc/apps/drywall_cutter_app/engine.py
Labels: member: Benji, status: ready for review, size: small PR, type: bug

#1742 Archie/refactor flurry
  src/asmcnc/apps/drywall_cutter_app/config/config_classes.py
  src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json
  src/asmcnc/apps/drywall_cutter_app/job_load_helper.py
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
  src/asmcnc/apps/start_up_sequence/screens/screen_safety_warning.py
  src/asmcnc/comms/flurry/__init__.py
  src/asmcnc/comms/flurry/flurry.py
  src/asmcnc/comms/flurry/tests/__init__.py
  src/asmcnc/comms/flurry/tests/test_flurry.py
  src/asmcnc/comms/localization.py
  src/asmcnc/comms/logging/log_exporter.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/comms/serial_connection.py
  src/main.py
  src/settings/settings_manager.py
  tests/manual_tests/experiments/experiment_toggle_reset_pin.py
Labels: member: Archie, status: ready for review, size: medium PR, priority: 1, type: feature

#1744 Add yeticut apps screen
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/skavaUI/img/Shapes_lobby_logo.png
  src/asmcnc/skavaUI/img/YetiCut_lobby_logo.png
  src/asmcnc/skavaUI/screen_lobby.py
  src/asmcnc/skavaUI/screen_yeticut_lobby.py
  src/main.py
Labels: size: medium PR, type: feature

#1746 Vp/tabs2
  src/asmcnc/apps/drywall_cutter_app/config/config_classes.py
  src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: member: Vlad, status: ready for review, size: small PR, type: feature

#1750 Allow dwt files to be loaded on dwt machines
  src/asmcnc/skavaUI/screen_local_filechooser.py
  src/asmcnc/skavaUI/screen_usb_filechooser.py
  src/jobCache/.gitignore
Labels: size: small PR, type: feature, project: dwt

#1752 Dwt file validation
  src/asmcnc/skavaUI/screen_file_loading.py
Labels: size: small PR, type: feature, project: dwt

#1754 Fix hold button for German/other languages
  src/asmcnc/core_UI/components/buttons/hold_button.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 1, type: bug

#1755 New buttons, new background colour, rearranged labels on tool/materia…
  src/asmcnc/apps/drywall_cutter_app/img/canvas_with_logo_dwt.png
  src/asmcnc/apps/drywall_cutter_app/img/circle_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/exit_button.png
  src/asmcnc/apps/drywall_cutter_app/img/go_button.png
  src/asmcnc/apps/drywall_cutter_app/img/home_button.png
  src/asmcnc/apps/drywall_cutter_app/img/line_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/open_button.png
  src/asmcnc/apps/drywall_cutter_app/img/rectangle_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/rotate_button.png
  src/asmcnc/apps/drywall_cutter_app/img/save_button.png
  src/asmcnc/apps/drywall_cutter_app/img/settings_button.png
  src/asmcnc/apps/drywall_cutter_app/img/simulate_button.png
  src/asmcnc/apps/drywall_cutter_app/img/square_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/stop_button.png
  src/asmcnc/apps/drywall_cutter_app/img/tool_and_material_button.png
  src/asmcnc/apps/drywall_cutter_app/img/toolpath_offset_inside_button.png
  src/asmcnc/apps/drywall_cutter_app/img/toolpath_offset_on_button.png
  src/asmcnc/apps/drywall_cutter_app/img/toolpath_offset_outside_button.png
  src/asmcnc/apps/drywall_cutter_app/img/toolpath_offset_pocket_button.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/apps/widget_tool_material_display.py
Labels: member: Archie, status: ready for review, size: medium PR, priority: 1

#1745 Benji/shapes lite/add finishing pass
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Labels: member: Benji, status: ready for review, size: small PR

#1758 updated german translation
  src/asmcnc/comms/foreign_dictionary.txt
Labels: member: Marc, status: ready for review, size: small PR, priority: 1, type: bug

#1759 Benji/shapes lite/new assets
  src/asmcnc/core_UI/utils/color_provider.py
  src/asmcnc/paths.py
  src/asmcnc/skavaUI/img/shapes_lobby_back_button.png
  src/asmcnc/skavaUI/img/shapes_lobby_logo.png
  src/asmcnc/skavaUI/img/shapes_lobby_toolbox_button.png
  src/asmcnc/skavaUI/img/trace_lobby_logo.png
  src/asmcnc/skavaUI/img/worktop_lobby_logo.png
  src/asmcnc/skavaUI/screen_yeticut_lobby.py
Labels: member: Benji, status: ready for review, size: small PR

#1751 Vp/tool and material popup
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/tool_material_popup.py
  src/asmcnc/job/database/__init__.py
  src/asmcnc/job/database/material_database.json
  src/asmcnc/job/database/profile_database.json
  src/asmcnc/job/database/profile_database.py
  src/asmcnc/job/database/tool_database.json
  src/main.py
Labels: member: Vlad, status: ready for review, size: medium PR, type: feature

#1762 Put fix for typing package onto hotfix branch
  src/asmcnc/core_UI/utils/color_provider.py
Labels: member: Letty, status: ready for review, size: small PR, priority: 1, type: bug

#1764 Remove MDF upcut profiles
  src/asmcnc/job/yetipilot/config/profiles.json
Labels: member: Letty, status: ready for review, size: small PR, priority: 2

#1765 Add release notes and update version
  src/main.py
  v290.txt
  v291.txt
Labels: member: Letty, status: ready for review, size: small PR, priority: 1

#1767 Add v290 file for completeness (and so I can screenshot for docs)
  v290.txt
Labels: member: Letty, status: ready for review, size: small PR, type: docs

#1776 Correct typo in profiles.json
  src/asmcnc/job/yetipilot/config/profiles.json
Labels: member: Benji, size: small PR, type: bug

#1774 Remove typing requirement
  ansible/init.yaml
  requirements.txt
  src/asmcnc/core_UI/utils/color_provider.py
Labels: member: Archie, status: ready for review, priority: 3

#1749 Benji/shapes lite/add pocketing
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
  src/asmcnc/apps/drywall_cutter_app/engine.py
Labels: member: Benji, status: ready for review, size: medium PR

#1771 Updated how the shape dimensions get checked
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
Labels: member: Vlad, status: ready for review, size: small PR, type: bug

#1768 Vp/dust shoe popup
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/comms/router_machine.py
  src/asmcnc/core_UI/new_popups/popup_bases.py
  src/asmcnc/core_UI/popup_manager.py
  src/asmcnc/core_UI/popups.py
  src/asmcnc/skavaUI/widget_quick_commands.py
Labels: member: Vlad, status: ready for review, size: medium PR, type: feature
