Repository YetiTool/easycut-smartbench, pull requests merged in 2024-05, with the labels that each got.

#1713 UserSettingsManager
  src/asmcnc/apps/maintenance_app/widget_maintenance_general_settings.py
  src/asmcnc/comms/model_manager.py
  src/asmcnc/comms/user_settings_manager.py
  src/main.py
  tests/automated_unit_tests/comms/test_user_settings_manager.py
Labels: member: Marc, status: ready for review, size: medium PR, priority: 2, type: feature

#1729 Placeholder for shapes app canvas
  src/asmcnc/apps/drywall_cutter_app/img/canvas_with_logo_shapes.png
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: size: small PR, type: feature

#1735 Show dwt on non dwt machines
  src/asmcnc/apps/app_manager.py
  src/asmcnc/skavaUI/screen_lobby.py
Labels: size: small PR, type: feature

#1730 Dwt update geberit
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_horizontal_8mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_6mm.gcode
  src/asmcnc/apps/drywall_cutter_app/gcode/geberit_111061001_vertical_8mm.gcode
  src/asmcnc/apps/drywall_cutter_app/img/geberit_horizontal_dims.png
  src/asmcnc/apps/drywall_cutter_app/img/geberit_vertical_dims.png
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: size: small PR, type: feature

#1733 Start of scaling up DWT for C10
  src/asmcnc/apps/drywall_cutter_app/image_dropdown.py
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Archie, size: medium PR, priority: 2, project: c10, project: dwt

#1731 DWT/Shapes cutter flag
  src/asmcnc/apps/app_manager.py
  src/asmcnc/apps/drywall_cutter_app/config/config_classes.py
  src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
  src/asmcnc/apps/drywall_cutter_app/config/config_options.py
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_45deg.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_60deg.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_8mm.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_90deg.json
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
Labels: member: Archie, status: ready for review, size: small PR, priority: 1, type: feature

#1732 Tool & Material Display Widget
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/widget_tool_material_display.py
Labels: member: Archie, size: small PR, priority: 1

#1736 Make experiment toggle test work again
  tests/manual_tests/experiments/experiment_toggle_reset_pin.py
Labels: member: Letty, status: ready for review, size: small PR, priority: 3, type: bug

#1728 updated flute length and max_depth_total for tool_6mm.json
  src/asmcnc/apps/drywall_cutter_app/config/cutters/tool_6mm.json
Labels: member: Vlad, status: ready for review, size: small PR

#1726 Vp/apps logging refactor
  src/asmcnc/apps/drywall_cutter_app/job_load_helper.py
Labels: member: Vlad, status: ready for review, size: small PR
