Repository YetiTool/easycut-smartbench, pull requests merged in 2024-07, with the labels that each got.

#1782 Changed "Auto pass" to "Auto pass depth"
  src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
Labels: member: Marc, status: ready for review, size: small PR, priority: 1, type: feature

#1783 Resize apps on yeticut lobby screen
  src/asmcnc/skavaUI/screen_yeticut_lobby.py
Labels: member: Dennis, size: small PR

#1784 Replace unit switch with mm label
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Dennis, size: small PR

#1791 Add rst files for japanese beta
  src/asmcnc/apps/start_up_sequence/data_consent_app/privacy_notice/JA.rst
  src/asmcnc/apps/wifi_app/wifi_documentation/日本語 (JA).rst
  src/asmcnc/comms/foreign_dictionary.txt
  src/asmcnc/comms/localization.py
  tests/manual_tests/experiments/experiment_fonts.py
Labels: member: Letty, status: ready for review, size: small PR, priority: 1, type: feature

#1792 Benji/shapes lite/fix whites
  src/asmcnc/apps/drywall_cutter_app/img/circle_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/line_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/rectangle_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/img/square_shape_button.png
  src/asmcnc/apps/drywall_cutter_app/widget_xy_move_drywall.py
  src/asmcnc/apps/widget_tool_material_display.py
Labels: member: Benji, status: ready for review, size: small PR, type: bug

#1794 Benji/shapes lite/line datum fix
  src/asmcnc/apps/drywall_cutter_app/engine.py
Labels: member: Benji, size: small PR, type: bug

#1788 Updated handling of config to update to new version automatically
  src/asmcnc/apps/drywall_cutter_app/config/config_classes.py
  src/asmcnc/apps/drywall_cutter_app/config/config_loader.py
  src/asmcnc/apps/drywall_cutter_app/config/configurations/test_config
  src/asmcnc/apps/drywall_cutter_app/config/migration/tool_migration_0_1.json
  src/asmcnc/apps/drywall_cutter_app/config/settings/default_config.json
  src/asmcnc/apps/drywall_cutter_app/material_setup_popup.py
  src/asmcnc/apps/drywall_cutter_app/screen_config_filechooser.py
  src/asmcnc/job/database/profile_database.json
  src/asmcnc/job/database/tool_database.json
Labels: member: Vlad, status: ready for review, size: medium PR, type: feature

#1787 Use active profile and cutter for yetipilot profile selection
  src/asmcnc/skavaUI/screen_go.py
Labels: member: Dennis, size: small PR

#1797 Japanese kana keyboard layout
  src/asmcnc/keyboard/custom_keyboard.py
  src/asmcnc/keyboard/layouts/ja.json
  src/asmcnc/keyboard/layouts/qwertyJA.json
Labels: member: Letty, status: ready for review, size: small PR, priority: 2

#1780 Benji/shapes lite/refactor
  src/asmcnc/apps/drywall_cutter_app/engine.py
  src/asmcnc/apps/drywall_cutter_app/engine_utils/__init__.py
  src/asmcnc/apps/drywall_cutter_app/engine_utils/tabutilities.py
Labels: member: Benji, status: ready for review, size: big PR

#1796 Account for tool diameter in min labels
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Dennis, size: small PR, type: feature

#1798 Add back to lobby button to serial failure screen
  src/asmcnc/skavaUI/screen_serial_failure.py
  tests/manual_tests/visual_screen_tests/visual_screen_tests.py
Labels: member: Dennis, size: small PR, type: feature

#1800 Don't set spindle on variable when in check state
  src/asmcnc/comms/serial_connection.py
Labels: member: Dennis, size: small PR, type: bug

#1801 Remove yeticut lobby
  src/asmcnc/apps/drywall_cutter_app/screen_drywall_cutter.py
  src/asmcnc/skavaUI/screen_lobby.py
Labels: member: Dennis, size: small PR

#1807 Align input canvas heights better
  src/asmcnc/apps/drywall_cutter_app/widget_drywall_shape_display.py
Labels: member: Dennis, size: small PR

#1805 Add dust shoe visuals to dust shoe alarm screen
  src/asmcnc/skavaUI/img/dust_shoe_plug.png
  src/asmcnc/skavaUI/img/dustshoe_plugs.png
  src/asmcnc/skavaUI/screen_dust_shoe_alarm.py
Labels: member: Dennis, size: small PR, type: feature

#1803 Japanese: Install mozcpy & mecab & dependencies
  ansible/host_vars/localhost
  ansible/init.yaml
  src/asmcnc/keyboard/custom_keyboard.py
Labels: member: Letty, status: ready for review, priority: 2
